\documentclass{article}\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlsng}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hldef}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage[margin=1.0in]{geometry} % To set margins
\usepackage{amsmath}  % This allows me to use the align functionality.
                      % If you find yourself trying to replicate
                      % something you found online, ensure you're
                      % loading the necessary packages!
\usepackage{amsfonts} % Math font
\usepackage{fancyvrb}
\usepackage{hyperref} % For including hyperlinks
\usepackage[shortlabels]{enumitem}% For enumerated lists with labels specified
                                  % We had to run tlmgr_install("enumitem") in R
\usepackage{float}    % For telling R where to put a table/figure
\usepackage{natbib}        %For the bibliography
\bibliographystyle{apalike}%For the bibliography
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}


\begin{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item A group of researchers is running an experiment over the course of 30 months, 
with a single observation collected at the end of each month. Let $X_1, ..., X_{30}$
denote the observations for each month. From prior studies, the researchers know that
\[X_i \sim f_X(x),\]
but the mean $\mu_X$ is unknown, and they wish to conduct the following test
\begin{align*}
H_0&: \mu_X = 0\\
H_a&: \mu_X > 0.
\end{align*}
At month $k$, they have accumulated data $X_1, ..., X_k$ and they have the 
$t$-statistic
\[T_k = \frac{\bar{X} - 0}{S_k/\sqrt{n}}.\]
The initial plan was to test the hypotheses after all data was collected (at the 
end of month 30), at level $\alpha=0.05$. However, conducting the experiment is 
expensive, so the researchers want to ``peek" at the data at the end of month 20 
to see if they can stop it early. That is, the researchers propose to check 
whether $t_{20}$ provides statistically discernible support for the alternative. 
If it does, they will stop the experiment early and report support for the 
researcher's alternative hypothesis. If it does not, they will continue to month 
30 and test whether $t_{30}$ provides statistically discernible support for the
alternative.

\begin{enumerate}
  \item What values of $t_{20}$ provide statistically discernible support for the
  alternative hypothesis?
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{set.seed}\hldef{(}\hlnum{5656}\hldef{)}
\hldef{alpha} \hlkwb{<-} \hlnum{0.05}
\hldef{n1} \hlkwb{<-} \hlnum{20}
\hldef{(t.20} \hlkwb{<-} \hlkwd{qt}\hldef{(}\hlnum{0.95}\hldef{,} \hlkwc{df} \hldef{= n1}\hlopt{-}\hlnum{1}\hldef{))}
\end{alltt}
\begin{verbatim}
## [1] 1.729133
\end{verbatim}
\end{kframe}
\end{knitrout}
Therefore $t_{20} \in [1.729133,\infty)$ provides statistically discernible support for the alternative hypothesis.
  \item What values of $t_{30}$ provide statistically discernible support for the
  alternative hypothesis?
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{n2} \hlkwb{<-} \hlnum{30}
\hldef{(t.30} \hlkwb{<-} \hlkwd{qt}\hldef{(}\hlnum{0.95}\hldef{,} \hlkwc{df} \hldef{= n2}\hlopt{-}\hlnum{1}\hldef{))}
\end{alltt}
\begin{verbatim}
## [1] 1.699127
\end{verbatim}
\end{kframe}
\end{knitrout}
Therefore $t_{30} \in [1.699127,\infty)$ provides statistically discernible support for the alternative hypothesis.
  \item Suppose $f_X(x)$ is a Laplace distribution with $a=0$ and $b=4.0$.
  Conduct a simulation study to assess the Type I error rate of this approach.\\
  \textbf{Note:} You can use the \texttt{rlaplace()} function from the \texttt{VGAM}
  package for \texttt{R} \citep{VGAM}.
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hldef{(VGAM)}
\hldef{a} \hlkwb{<-} \hlnum{0}
\hldef{b} \hlkwb{<-} \hlnum{4}
\hldef{it} \hlkwb{<-} \hlnum{1000}
\hldef{reject.count} \hlkwb{<-} \hlnum{0}

\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{it)\{}
  \hldef{x} \hlkwb{<-} \hlkwd{rlaplace}\hldef{(n2, a, b)}
  \hldef{t20} \hlkwb{<-} \hlkwd{mean}\hldef{(x[}\hlnum{1}\hlopt{:}\hldef{n1])}\hlopt{/}\hldef{(}\hlkwd{sd}\hldef{(x[}\hlnum{1}\hlopt{:}\hldef{n1])}\hlopt{/}\hlkwd{sqrt}\hldef{(n1))}
  \hlkwa{if}\hldef{(t20} \hlopt{>=} \hldef{t.20)\{}
    \hldef{reject.count} \hlkwb{<-} \hldef{reject.count} \hlopt{+} \hlnum{1}
  \hldef{\}}
\hldef{\}}
\hldef{(error.rate} \hlkwb{<-} \hldef{reject.count} \hlopt{/} \hldef{it)}
\end{alltt}
\begin{verbatim}
## [1] 0.052
\end{verbatim}
\end{kframe}
\end{knitrout}
Therefore the Type I error rate is 0.052.
  \item \textbf{Optional Challenge:} Can you find a value of $\alpha<0.05$ that yields a 
  Type I error rate of 0.05?
\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  \item Perform a simulation study to assess the robustness of the $T$ test. 
  Specifically, generate samples of size $n=15$ from the Beta(10,2), Beta(2,10), 
  and Beta(10,10) distributions and conduct the following hypothesis tests against 
  the actual mean for each case (e.g., $\frac{10}{10+2}$, $\frac{2}{10+2}$, and 
  $\frac{10}{10+10}$). 
  \begin{enumerate}
    \item What proportion of the time do we make an error of Type I for a
    left-tailed test?
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{n} \hlkwb{<-} \hlnum{15}
\hldef{a1} \hlkwb{<-} \hlnum{10}
\hldef{a2} \hlkwb{<-} \hlnum{2}
\hldef{b1} \hlkwb{<-} \hlnum{2}
\hldef{b2} \hlkwb{<-} \hlnum{10}
\hldef{mean1} \hlkwb{<-} \hldef{a1}\hlopt{/}\hldef{(a1}\hlopt{+}\hldef{b1)}
\hldef{mean2} \hlkwb{<-} \hldef{a2}\hlopt{/}\hldef{(a2}\hlopt{+}\hldef{b2)}
\hldef{mean3} \hlkwb{<-} \hldef{a1}\hlopt{/}\hldef{(a1}\hlopt{+}\hldef{b2)}
\hldef{tcrit.one} \hlkwb{<-} \hlkwd{qt}\hldef{(}\hlnum{0.95}\hldef{,} \hlkwc{df} \hldef{= n}\hlopt{-}\hlnum{1}\hldef{)}
\hldef{tcrit.two} \hlkwb{<-} \hlkwd{qt}\hldef{(}\hlnum{0.975}\hldef{,} \hlkwc{df} \hldef{= n}\hlopt{-}\hlnum{1}\hldef{)}
\hldef{rej.left.10.2} \hlkwb{<-} \hlnum{0}
\hldef{rej.left.2.10} \hlkwb{<-} \hlnum{0}
\hldef{rej.left.10.10} \hlkwb{<-} \hlnum{0}
\hldef{rej.right.10.2} \hlkwb{<-} \hlnum{0}
\hldef{rej.right.2.10} \hlkwb{<-} \hlnum{0}
\hldef{rej.right.10.10} \hlkwb{<-} \hlnum{0}
\hldef{rej.two.10.2} \hlkwb{<-} \hlnum{0}
\hldef{rej.two.2.10} \hlkwb{<-} \hlnum{0}
\hldef{rej.two.10.10} \hlkwb{<-} \hlnum{0}

\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{it)\{}
  \hldef{b.10.2} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,a1,b1)}
  \hldef{t.10.2} \hlkwb{<-} \hldef{(}\hlkwd{mean}\hldef{(b.10.2)}\hlopt{-}\hldef{mean1)} \hlopt{/} \hldef{(}\hlkwd{sd}\hldef{(b.10.2)}\hlopt{/}\hlkwd{sqrt}\hldef{(n))}
  \hldef{b.2.10} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,a2,b2)}
  \hldef{t.2.10} \hlkwb{<-} \hldef{(}\hlkwd{mean}\hldef{(b.2.10)}\hlopt{-}\hldef{mean2)} \hlopt{/} \hldef{(}\hlkwd{sd}\hldef{(b.2.10)}\hlopt{/}\hlkwd{sqrt}\hldef{(n))}
  \hldef{b.10.10} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,a1,b2)}
  \hldef{t.10.10} \hlkwb{<-} \hldef{(}\hlkwd{mean}\hldef{(b.10.10)}\hlopt{-}\hldef{mean3)} \hlopt{/} \hldef{(}\hlkwd{sd}\hldef{(b.10.10)}\hlopt{/}\hlkwd{sqrt}\hldef{(n))}
  \hlkwa{if}\hldef{(t.10.2} \hlopt{<= -}\hldef{tcrit.one)\{}
    \hldef{rej.left.10.2} \hlkwb{<-} \hldef{rej.left.10.2} \hlopt{+} \hlnum{1}
  \hldef{\}}
  \hlkwa{if}\hldef{(t.2.10} \hlopt{<= -}\hldef{tcrit.one)\{}
    \hldef{rej.left.2.10} \hlkwb{<-} \hldef{rej.left.2.10} \hlopt{+} \hlnum{1}
  \hldef{\}}
  \hlkwa{if}\hldef{(t.10.10} \hlopt{<= -}\hldef{tcrit.one)\{}
    \hldef{rej.left.10.10} \hlkwb{<-} \hldef{rej.left.10.10} \hlopt{+} \hlnum{1}
  \hldef{\}}
  \hlkwa{if}\hldef{(t.10.2} \hlopt{>=} \hldef{tcrit.one)\{}
    \hldef{rej.right.10.2} \hlkwb{<-} \hldef{rej.right.10.2} \hlopt{+} \hlnum{1}
  \hldef{\}}
  \hlkwa{if}\hldef{(t.2.10} \hlopt{>=} \hldef{tcrit.one)\{}
    \hldef{rej.right.2.10} \hlkwb{<-} \hldef{rej.right.2.10} \hlopt{+} \hlnum{1}
  \hldef{\}}
  \hlkwa{if}\hldef{(t.10.10} \hlopt{>=} \hldef{tcrit.one)\{}
    \hldef{rej.right.10.10} \hlkwb{<-} \hldef{rej.right.10.10} \hlopt{+} \hlnum{1}
  \hldef{\}}
  \hlkwa{if}\hldef{(t.10.2} \hlopt{<= -}\hldef{tcrit.two} \hlopt{|} \hldef{t.10.2} \hlopt{>=} \hldef{tcrit.two)\{}
    \hldef{rej.two.10.2} \hlkwb{<-} \hldef{rej.two.10.2} \hlopt{+} \hlnum{1}
  \hldef{\}}
  \hlkwa{if}\hldef{(t.2.10} \hlopt{<= -}\hldef{tcrit.two} \hlopt{|} \hldef{t.2.10} \hlopt{>=} \hldef{tcrit.two)\{}
    \hldef{rej.two.2.10} \hlkwb{<-} \hldef{rej.two.2.10} \hlopt{+} \hlnum{1}
  \hldef{\}}
  \hlkwa{if}\hldef{(t.10.10} \hlopt{<= -}\hldef{tcrit.two} \hlopt{|} \hldef{t.10.10} \hlopt{>=} \hldef{tcrit.two)\{}
    \hldef{rej.two.10.10} \hlkwb{<-} \hldef{rej.two.10.10} \hlopt{+} \hlnum{1}
  \hldef{\}}
\hldef{\}}
\hldef{(error.left.10.2} \hlkwb{<-} \hldef{rej.left.10.2} \hlopt{/} \hldef{it)}
\end{alltt}
\begin{verbatim}
## [1] 0.023
\end{verbatim}
\begin{alltt}
\hldef{(error.left.2.10} \hlkwb{<-} \hldef{rej.left.2.10} \hlopt{/} \hldef{it)}
\end{alltt}
\begin{verbatim}
## [1] 0.074
\end{verbatim}
\begin{alltt}
\hldef{(error.left.10.10} \hlkwb{<-} \hldef{rej.left.10.10} \hlopt{/} \hldef{it)}
\end{alltt}
\begin{verbatim}
## [1] 0.056
\end{verbatim}
\end{kframe}
\end{knitrout}
Therefore the Type I error rate for a left-tailed test ranges from 0.023 to 0.074 in our set of distributions.
    \item What proportion of the time do we make an error of Type I for a
    right-tailed test?
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{(error.right.10.2} \hlkwb{<-} \hldef{rej.right.10.2} \hlopt{/} \hldef{it)}
\end{alltt}
\begin{verbatim}
## [1] 0.078
\end{verbatim}
\begin{alltt}
\hldef{(error.right.2.10} \hlkwb{<-} \hldef{rej.right.2.10} \hlopt{/} \hldef{it)}
\end{alltt}
\begin{verbatim}
## [1] 0.022
\end{verbatim}
\begin{alltt}
\hldef{(error.right.10.10} \hlkwb{<-} \hldef{rej.right.10.10} \hlopt{/} \hldef{it)}
\end{alltt}
\begin{verbatim}
## [1] 0.055
\end{verbatim}
\end{kframe}
\end{knitrout}
Therefore the Type I error rate for a right-tailed test ranges from 0.022 to 0.078 in our set of distributions.
    \item What proportion of the time do we make an error of Type I for a
    two-tailed test?
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{(error.two.10.2} \hlkwb{<-} \hldef{rej.two.10.2} \hlopt{/} \hldef{it)}
\end{alltt}
\begin{verbatim}
## [1] 0.059
\end{verbatim}
\begin{alltt}
\hldef{(error.two.2.10} \hlkwb{<-} \hldef{rej.two.2.10} \hlopt{/} \hldef{it)}
\end{alltt}
\begin{verbatim}
## [1] 0.052
\end{verbatim}
\begin{alltt}
\hldef{(error.two.10.10} \hlkwb{<-} \hldef{rej.two.10.10} \hlopt{/} \hldef{it)}
\end{alltt}
\begin{verbatim}
## [1] 0.054
\end{verbatim}
\end{kframe}
\end{knitrout}
Therefore the Type I error rate for a two-tailed test ranges from 0.052 to 0.059 in our set of distributions.
    \item How does skewness of the underlying population distribution effect
    Type I error across the test types?
    
In a right-skewed distribution, e.g. Beta(10,2), the Type I error rate from a left-tailed test is substantially lower (0.023), while the error rate from a right-tailed test is substantially higher (0.078). In a left-skewed distribution, e.g. Beta(2,10), the reverse effect is present (0.074 vs. 0.022). In a symmetric distribution, e.g. Beta(10,10), error rate is not significantly impacted by the chosen t-test (ranges from 0.054 to 0.056).
  \end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% End Document
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\end{enumerate}
\bibliography{bibliography}
\end{document}
